### ISSUE TITLE
Incorrect rendering on iOS

### ISSUE THREAD

**Issue by gymnae** [onebeartoe/electronics#3]
First: I love this little application! I started to learn python to code myself a version with more layout options, but never really got far.

But now to the bug: Since iOS 12 it appears that the rendering of the animations and images to select is broken, please see screenshot. 

![Simulator Screen Shot - iPhone Xʀ - 2019-09-13 at 17 24 55](https://user-images.githubusercontent.com/6195487/64874512-724c3900-d64b-11e9-9b5b-a2a44bf16db0.png)

Is there a way to fix this?

On a related note: The links in the adafruit learn page for snaptshops lead to a dead end, so I cam stuck with the version of this .war posted on the adafruit pages.

Cheers

**Comment by onebeartoe** [comment]
hey @Gymnae, I am not sure how to correct this for iOS 'anything'

Please consult with Adafruit on their forums.

**Comment by onebeartoe** [comment]
I don't have a iOS device to test this.
